### ISSUE TITLE
Error : cannot assign a value to variable LightGraphs.Graph from module Main

### ISSUE THREAD

**Issue by Myrddinlefou** [sbromberger/MetaGraphs.jl#100]
Hello,

I want to create graph with a function, and when I use this code I have the error in the title.

`using LightGraphs, MetaGraphs

function NewGraph()
    g = Graph(1)
    println(g)
    mg = MetaGraph(g)
    println(mg)
    return (g)
end

Graph = NewGraph()
`

Did you know how I can do that ?
****
Thanks a lot.

**Comment by sbromberger** [comment]
the word `Graph` is exported by LightGraphs as a type (you're even using it on line 1 of your function) so you can't use it as a variable.

**Comment by Myrddinlefou** [comment]
It’s work, sorry for the stupid question…

Many thanks.
