### ISSUE TITLE
Current best library for plotting MetaGraph with properties?

### ISSUE THREAD

**Issue by nickeubank** [sbromberger/MetaGraphs.jl#18]
Would love to do things like set vertex size with a vertex property, or label vertices with MetaGraph vertex properties. 

Few listed here: http://juliagraphs.github.io/LightGraphs.jl/latest/plotting.html but little on integration...

**Comment by sbromberger** [comment]
I'd take a look at GraphPlot.jl and PlotRecipes (for Plots).

**Comment by nickeubank** [comment]
Thanks!
