### ISSUE TITLE
Check if graph is empty

### ISSUE THREAD

**Issue by bisraelsen** [sbromberger/MetaGraphs.jl#20]
Hi, I'd like to check if a graph is empty or not.

When I create a graph using `MetaGraph()` the printed output says:

    empty undirected Int64 metagraph with Float64 weights defined by :weight (default weight 1.0)

Attempting to use `isempty` doesn't work because it is not defined for `MetaGraph` input. Is there a different function that returns whether a graph is empty? If not, what might be a decent approach so that I can make one.

I suppose this might, more fundamentally, apply to LightGraphs. Perhaps the code belongs there....

Thanks!

**Comment by sbromberger** [comment]
It really depends on your definition of emptiness. You could check to see whether `nv(g) == 0`, or if you consider a graph to be empty if there are no edges, `ne(g) == 0`.

**Comment by bisraelsen** [comment]
I guess I am wondering what the current approach for classifying a graph as `empty` is (as I stated above, the graph is already deemed `empty` by some criteria). Does using `MetaGraph()` yield an empty graph because `nv(g)==0`? I believe that is what is happening because invoking `MetaGraph(2)` yields:

    {2, 0} undirected Int64 metagraph with Float64 weights defined by :weight (default weight 1.0) 

I.e. `nv(g)>0` is not empty. In the end, I guess it would be nice to have an `isempty` function for Light/MetaGraphs. And it seems the current criteria for emptiness is `nv(g)==0`.

Perhaps I'll implement `isempty` for doing that...

**Comment by sbromberger** [comment]
Are you concerned with the wording of `show` for a graph with zero vertices? I used "empty" there to denote no vertices (which also implies no edges). It wasn't a technical decision; it just seemed to describe `Graph()` most efficiently. I'm open to changing the text if you've got a better alternative.

**Comment by sbromberger** [comment]
...and `isempty` implies iteration, so that's probably a bad idea to implement since we've made a conscious decision to not let graphs themselves be iterable.

**Comment by bisraelsen** [comment]
I am not concerned with the wording, just trying to find out how to check whether a graph is `empty` as described. On my first time through I saw that `MetaGraph()` was described as `empty`, and was subsequently surprised when `isempty` didn't function.

I understand that the graph shouldn't be iterable, but in my opinion I think it makes sense to think of the graph as a *collection* (on which `isempty` is classically defined) of nodes and edges, and thus that it is reasonable to apply `isempty` to a graph.

Regardless, I now know that `nv(g)==0` is the criteria, and can use that instead. Thanks for your help!

**Comment by sbromberger** [comment]
> in my opinion I think it makes sense to think of the graph as a collection... of nodes and edges

We have tended to think of it as two collections: one of vertices, and one of edges. Indeed, both vertices and edges are iterable.

> on which `isempty` is classically defined

Which gets to the ambiguity when `nv(g) > 0` and `ne(g) == 0`. Is a two-vertex, no-edge graph empty, or not?

**Comment by bisraelsen** [comment]
I see.

Perhaps then `MetaGraph()` should return:

    {0, 0} undirected Int64 metagraph with Float64 weights defined by :weight (default weight 1.0) 

and avoid the "empty" word altogether.

I suppose the "empty" I am talking about is when both `vertices(g)` ***and*** `edges(g)` are empty... I think `isempty(vertices(g))` is sufficient for this to be true. On principle it seems to me that there should be a simple (i.e. a single function) way to return whether a graph was created "empty" using `MetaGraph()` or `Graph()`. 

However, I am not sure if this fits within the way you want to approach things. In that case checking `nv(g)==0` can work for me.

**Comment by sbromberger** [comment]
> `{0, 0} undirected Int64`

This makes sense and I'll make a PR for it. Thanks. :)
