### ISSUE TITLE
convert  `MetaWeights` object to matrix

### ISSUE THREAD

**Issue by scheidan** [sbromberger/MetaGraphs.jl#27]
Great package, thanks!

The function `weights(g::SimpleWeightedGraphs.SimpleWeightedGraph)` return a (sparse) matrix of the weights, while `weights(g::MetaGraphs.MetaDiGraph)` returns a `MetaWeights` object. Is there a built-in way to convert this to a matrix?

**Comment by sbromberger** [comment]
```
Matrix(weights(m))
```
or
```
sparse(weights(m))
```
depending on whether you want a dense or sparse matrix.

**Comment by sbromberger** [comment]
@scheidan - ok if I close this out?
