### ISSUE TITLE
Type stable version?

### ISSUE THREAD

**Issue by bramtayl** [sbromberger/MetaGraphs.jl#30]
Metadata as `Dict{Symbol,Any}` is type unstable. If you know that each node will have the same typed metadata, it might make more sense to have these be named tuples instead?

**Comment by sbromberger** [comment]
Yes. I was thinking about how best to do this. Could you make a PR for discussion?

**Comment by bramtayl** [comment]
I started looking into this, and even prepping a PR. Ended up being a lot more work than I expected, but here's how I was thinking of going about it:

```julia
import LightGraphs: AbstractGraph, SimpleEdge

struct MetaGraph{Eltype, Graph <: AbstractGraph{Eltype}, VertexMeta, EdgeMeta, GraphMeta} <: AbstractGraph{Eltype}
    graph::Graph
    vertex_dict::Dict{Eltype, VertexMeta}
    vertex_default::VertexMeta
    edge_dict::Dict{SimpleEdge{Eltype}, EdgeMeta}
    edge_default::EdgeMeta
    graph_meta::GraphMeta
end

function MetaGraph(graph::AbstractGraph{Eltype};
    vertex_default::VertexMeta = nothing, 
    edge_default::EdgeMeta = nothing, 
    graph_meta::GraphMeta = nothing) where {Eltype, VertexMeta, EdgeMeta, GraphMeta}
    vertex_dict = Dict{Eltype, VertexMeta}()
    edge_dict = Dict{SimpleEdge{Eltype}, EdgeMeta}()
    MetaGraph(graph, vertex_dict, vertex_default, edge_dict, edge_default, graph_meta)
end
```

**Comment by bramtayl** [comment]
Eh, I've decided if you realize want something type stable, setting up a Dict from vertices/edges to something of a fixed type isn't to hard to do yourself.

**Comment by sbromberger** [comment]
I was actually hoping you had a good solution to this!

**Comment by bramtayl** [comment]
It's definitely possible but I don't really have time. I think the snipped about could leave some breadcrumbs.
