### ISSUE TITLE
dijkstra_shortest_paths() doesn't accept graph of type MetaGraphs

### ISSUE THREAD

**Issue by elchiconuevo** [sbromberger/MetaGraphs.jl#31]
I'm solving the shortest path problem on a graph modelled using MetaGraphs.jl package. The function `dijkstra_shortest_paths()` returns an error.
`ERROR: LoadError: MethodError: no method matching dijkstra_shortest_paths(::MetaGraphs.MetaDiGraph{Int64,Float64}, ::Int64, ::Int64)`. Is there a way around this problem or do I have to switch to `SimpleWeightedGraphs.jl` to model my graph?

**Comment by sbromberger** [comment]
Why are you passing two integers to `dijkstra`?

**Comment by elchiconuevo** [comment]
The second integer (the sink node) was meant for another function `enumerate_paths`. This was a typo

**Comment by sbromberger** [comment]
So are you still having a problem?
```
julia> m = MetaDiGraph(DiGraph(10,20))
{10, 20} directed Int64 metagraph with Float64 weights defined by :weight (default weight 1.0)

julia> dijkstra_shortest_paths(m, 1)
LightGraphs.DijkstraState{Float64,Int64}([0, 5, 7, 2, 1, 10, 5, 9, 5, 1], [0.0, 2.0, 3.0, 3.0, 1.0, 2.0, 2.0, 3.0, 2.0, 1.0], Array{Int64,1}[Int64[], Int64[], Int64[], Int64[], Int64[], Int64[], Int64[], Int64[], Int64[], Int64[]], [1, 2, 3, 2, 1, 1, 1, 3, 2, 1], Int64[])
```

**Comment by elchiconuevo** [comment]
No, this was a non-issue. It was a typo that caused this error.

**Comment by sbromberger** [comment]
Glad to hear - thanks for the update.
