### ISSUE TITLE
Issue reversing a metagraph with function "reverse()"

### ISSUE THREAD

**Issue by Alexorhn** [sbromberger/MetaGraphs.jl#35]
Hi,
I am currently working on Julia with the MetaGraphs.jl package.

I have created the Graph with a dataset, the characteristic of the graph is that there's one start vertex and one end vertex. However the graph is created by creating all possible options so some edges which "take too much time" don't reach the final vertex. In order to have a decent graph for my next step/ an optimization problem. I am cleaning the graph by simply going through all edges and those who don't reach the end vertex are deleted. But this method is costly in time and I know a wiser way to do it. The method is simple:

1. reversing the graph (end vertex becomes start vertex) 
2. Calculating the distance of all vertices from the start vertex 
3. erase the vertices which don't have a defined distance with the start vertex

I have created an example of a small digraph that would be the same type as mine:

```
module EssaiModule
using LightGraphs, MetaGraphs

g = DiGraph(8)
mg = MetaDiGraph(g, 1.0)

add_vertex!(mg)
add_edge!(mg,1,2)
add_edge!(mg,1,3)
add_edge!(mg,1,4)
add_edge!(mg,2,4)
add_edge!(mg,2,5)
add_edge!(mg,3,5)
add_edge!(mg,5,6)
add_edge!(mg,4,6)
add_edge!(mg,3,7)
add_edge!(mg,4,8)

rg=reverse(mg)

end
```
the end vertex is number 6 so normally I would like to erase edges 3->7 and 4->8 But I can't even start my function because **I simply cannot reverse this graph.**

I get the error message "**_LoadError: type MetaDiGraph has no field badjlist_**" I know it's because the graph is a metaGraph and not a lightGraph but shouldn't we be able to reverse a metagraph? it seems like a basic function that could be useful on many occasions while working with graphs.

**Comment by sbromberger** [comment]
The functions in `operators.jl`, including `reverse`, are currently not implemented for MetaGraphs. This would make a good PR.

**Comment by sbromberger** [comment]
ref #36
