### ISSUE TITLE
consistent handling of weight property

### ISSUE THREAD

**Issue by ExpandingMan** [sbromberger/MetaGraphs.jl#37]
Right now if you do `get_prop(mg, 1, 2, :weight)` you get an error if `Edge(1,2)` uses the default weight.  It would be nice if you always get the weight.  Right now this would give a performance hit unless the `:weight` key is explicitly added to the `Dict`, so I'm not sure what the best way of handling it would be.  Perhaps it would be worth adding a `getweight` function?  I don't see that in the docs.

**Comment by sbromberger** [comment]
there is a `weights(g::AbstractGraph)` function that is supposed to return the weight of the edge indexed by `[src, dst]`:

```
julia> g = Graph(10,20)
{10, 20} undirected simple Int64 graph

julia> weights(g)[1,3] # default weight will return `1` even if the edge doesn't exist.
1

julia> sg = WGraph(g)  # SimpleWeightedGraph constructor
{10, 20} undirected simple Int64 graph with Float64 weights

julia> add_edge!(sg, 1, 3, 6)
WARNING: Note: adding edges to this graph type is not performant.
true

julia> weights(sg)[1,3] #  SWGs will return `0.0` if the edge doesn't exist.
6.0

julia> mg = MetaGraph(g)

julia> set_prop!(mg, 1, 3, :weight, 6.0)
Dict{Symbol,Float64} with 1 entry:
  :weight => 6.0

julia> weights(mg)[1,3]
6.0

julia> weights(mg)[1,2]  # this edge doesn't exist
1.0

```

**Comment by sbromberger** [comment]
Also: `:weight` is simply another label in MetaGraphs. It only gains importance because it's the default `weightfield`. You could just as easily do `weightfield!(mg, :my_custom_weight)` to use that symbol. `weights()` is (should be) the universal way to get a weight from any type of edge, regardless of graph type.

**Comment by ExpandingMan** [comment]
Ah, well that makes the design philosophy much clearer at least, thanks.  It was bothering me that the weights are treated in a way that I find inconsistent with the other properties (well, perhaps that's not the right description, at least the default weights seemed inconsistent with the other properties).

I think I see now that you did it this way because only metagraphs have properties dictionaries, but multiple graph types have weights.

Anyway, I still think it would be nice if you could do `get_prop(mg, 1, 3, :weight) for the default weights, but perhaps I'm still not fully grokking the design.  Regardless, this isn't necessarily actionable so I'll close the issue.  Thanks again.
