### ISSUE TITLE
weakly_connected_components fails with directed MetaGraphs

### ISSUE THREAD

**Issue by sethchandler** [sbromberger/MetaGraphs.jl#38]
weakly_connected_components generates the following error consistently when used with a directed MetaGraph.

MethodError: Cannot `convert` an object of type MetaGraphs.MetaDiGraph{Int64,Float64} to an object of type LightGraphs.SimpleGraphs.SimpleGraph
This may have arisen from a call to the constructor LightGraphs.SimpleGraphs.SimpleGraph(...),
since type constructors fall back to convert methods.

I attach a Jupyter notebook file and a Julia (jl) file that should show the issue.
[weaklyconnected.zip](https://github.com/JuliaGraphs/MetaGraphs.jl/files/2074459/weaklyconnected.zip)

**Comment by sbromberger** [comment]
This is a known issue; see also https://github.com/JuliaGraphs/LightGraphs.jl/issues/853.

**Comment by sbromberger** [comment]
If you need the weakly connected components for a metagraph `mg`, the best way to handle this right now is to do this:

```
weakly_connected_components(mg.graph)
```

**Comment by sethchandler** [comment]
Thanks so much for the work-around. Just tried it. Success!  Working on a 3 million node, 30 million edge graph that represents a legal citation network.

**Comment by sbromberger** [comment]
That's very cool! Thanks for the update.
