### ISSUE TITLE
use new iterator Base function

### ISSUE THREAD

**Issue by xiuliren** [sbromberger/MetaGraphs.jl#51]
Julia 0.7 introduced new iterator interface.
The Base: start, next, done functions were deprecated.
https://julialang.org/blog/2018/07/iterators-in-julia-0.7

**Comment by sbromberger** [comment]
I don't think we've got any iterators to begin with. Are you seeing an issue?

**Comment by sbromberger** [comment]
Ah, yes. Fixed via #52.
