### ISSUE TITLE
set_prop!/set_props! return nothing

### ISSUE THREAD

**Issue by gdkrmr** [sbromberger/MetaGraphs.jl#57]
```julia
julia> g = MetaDiGraph()
{0, 0} directed Int64 metagraph with Float64 weights defined by :weight (default weight 1.0)

julia> add_vertex!(g)
true

julia> set_prop!(g, 1, 2, :name, "hello2")

julia> set_props!(g, 1, 2, Dict(:name => "hello2"))

julia> g.eprops
Dict{LightGraphs.SimpleGraphs.SimpleEdge{Int64},Dict{Symbol,Any}} with 0 entries

```
to be consistent with `LightGraphs`, `set_prop!` and `set_props!` should return a `Bool`.

**Comment by sbromberger** [comment]
The documentation is inconsistent in any case:
> Will return false if vertex or edge does not exist, true otherwise

What actually happens is that the prop is returned if it succeeds, and `nothing` is returned if failed. This should be fixed.
