### ISSUE TITLE
MetaGraph of directed graph?

### ISSUE THREAD

**Issue by thvhauwe** [sbromberger/MetaGraphs.jl#59]
When I want to make a metagraph of a directed graph object, the underlying graph becomes an undirected graph? This behaviour is unwanted.
![metagraph](https://user-images.githubusercontent.com/42406846/48904941-6abf6780-ee60-11e8-956b-8efc6ec06722.png)

**Comment by sbromberger** [comment]
If you want a directed graph, use the `MetaDiGraph` constructor instead.

**Comment by thvhauwe** [comment]
Thanks!
