### ISSUE TITLE
reverse() on MetaDiGraph reverses vertex properties unneccessarily

### ISSUE THREAD

**Issue by DanBerge** [sbromberger/MetaGraphs.jl#67]
Reversing a `MetaDiGraph` reverses the vertex properties unecessarily.

```
begin
    g=MetaDiGraph(StarDiGraph(4))
    set_indexing_prop!(g,:nodelabel)
    foreach(v->set_indexing_prop!(g,v,:nodelabel,"Vertex $v"),vertices(g))
    foreach(e->set_prop!(g,e,:edgelabel,"Edge ($(e.src),$(e.dst))"),edges(g))
end
```

The functionality besides the `vprops` appear to be correct.

```
g.graph.fadjlist==reverse(g).graph.badjlist #true as expected
g.graph.badjlist==reverse(g).graph.fadjlist #true as expected
get_prop(g,1,2,:edgelabel)==get_prop(reverse(g),2,1,:edgelabel) # true as expected
```

Vertex properties are incorrect
```
g["Vertex 1",:nodelabel]==reverse(g)["Vertex 1",:nodelabel] #false, which is not correct
```

`vprops` keys are reversed, causing the issue.

```
g.vprops
Dict{Int64,Dict{Symbol,Any}} with 4 entries:
  4 => Dict{Symbol,Any}(:nodelabel=>"Vertex 4")
  2 => Dict{Symbol,Any}(:nodelabel=>"Vertex 2")
  3 => Dict{Symbol,Any}(:nodelabel=>"Vertex 3")
  1 => Dict{Symbol,Any}(:nodelabel=>"Vertex 1")

reverse(g).vprops
Dict{Int64,Dict{Symbol,Any}} with 4 entries:
  4 => Dict{Symbol,Any}(:nodelabel=>"Vertex 1")
  2 => Dict{Symbol,Any}(:nodelabel=>"Vertex 3")
  3 => Dict{Symbol,Any}(:nodelabel=>"Vertex 2")
  1 => Dict{Symbol,Any}(:nodelabel=>"Vertex 4")
```

The forward graph
![forward graph](https://user-images.githubusercontent.com/36931035/51945056-26fa5880-23e3-11e9-87ce-2ee5783e68d9.png)

and the incorrect `reverse(g)`
![reverse graph](https://user-images.githubusercontent.com/36931035/51945032-14801f00-23e3-11e9-9b3e-1f5dbd465483.png)

The correct `reverse(g)` should be 
![corrected graph](https://user-images.githubusercontent.com/36931035/51945122-5d37d800-23e3-11e9-9beb-3ce662d80077.png)

**Comment by sbromberger** [comment]
Big thanks for the great problem report (especially the diagrams).
