### ISSUE TITLE
rem_vertex! fails if indexing_props is set

### ISSUE THREAD

**Issue by Affie** [sbromberger/MetaGraphs.jl#72]
```
The following properties are indexing_props and cannot be updated: Set(Symbol[:label])
in top-level scope at base/none
in rem_vertex! at MetaGraphs/kAvjf/src/MetaGraphs.jl:155
in set_props! at MetaGraphs/kAvjf/src/MetaGraphs.jl:274
in error at base/error.jl:33
```

**Comment by DanBerge** [comment]
This issue was addressed by #73 .

**Comment by sbromberger** [comment]
Closed via #73.

**Comment by Affie** [comment]
Thanks for this, It seems to work well now.
@sbromberger Can you possibly tag a new version, we want to start using it in another package.

**Comment by sbromberger** [comment]
The new version has already been tagged; we're still working on getting the registry updated. Hopefully later today.
