### ISSUE TITLE
Package MetaGraphs does not have Random in its dependencies

### ISSUE THREAD

**Issue by coroa** [sbromberger/MetaGraphs.jl#81]
Since updating to v0.6.2, I'm seeing new warnings

```
┌ Warning: Package MetaGraphs does not have Random in its dependencies:
│ - If you have MetaGraphs checked out for development and have
│   added Random as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with MetaGraphs
└ Loading Random into MetaGraphs from project dependency, future warnings for MetaGraphs are suppressed.
```

**Comment by sbromberger** [comment]
yup. Random is in stdlib so this shouldn't impact your usage at all. We'll be issuing a fix shortly.

**Comment by coroa** [comment]
Great, thanks

**Comment by coroa** [comment]
Your fix works for me!

**Comment by davidanthoff** [comment]
Could we merge that branch and then tag a new release? The error message is a bit annoying :)

**Comment by davidanthoff** [comment]
Actually, it is not just the optics, without the fix all precompile is broken for all downstream packages, which is really quite bad. If there is any chance we could tag a new release today it would be great. I have a workshop coming up where we need all of this, and this is causing quite a bit of problems :) Any help here is much appreciated!

**Comment by sbromberger** [comment]
I will try to make a release today.

**Comment by sbromberger** [comment]
#82

**Comment by davidanthoff** [comment]
I think you first need to actually merge the branch with the fix into `master` and then tag a release, the latest release still doesn't fix this.

**Comment by sbromberger** [comment]
> I think you first need to actually merge the branch with the fix into master and then tag a release, the latest release still doesn't fix this.

~~There was no branch; I merged it directly into master before #82.~~

Oh, no, that's wrong. There was a branch. One sec.

**Comment by davidanthoff** [comment]
Excellent, much appreciated!

**Comment by sbromberger** [comment]
Yeah. Sorry about that. It was a bit messy.
