### ISSUE TITLE
Why does savedot only support a directed graph? 

### ISSUE THREAD

**Issue by Affie** [sbromberger/MetaGraphs.jl#86]
It seems to do the same thing but is fixed on a MetaDiGraph: 
https://github.com/JuliaGraphs/MetaGraphs.jl/blob/56154277d0679049c3542a65d812014ef987161c/src/persistence.jl#L19

**Comment by diegozea** [comment]
I've just found the same problem trying to save a `MetaGraph` for posterior visualization in *Cytoscape*.
