### ISSUE TITLE
How to create loop graph?

### ISSUE THREAD

**Issue by zhaoli-IHEP** [sbromberger/MetaGraphs.jl#91]
For example, two edges connecting "same" two vertices, like --O--
```julia
g = Graph(4)
add_edge!(g,1,2) # this is okay
add_edge!(g,1,2) # but this will fail
```
I have checked also MetaGraph, but did not find any information about this.

**Comment by simonschoelly** [comment]
I think what you probably mean is a [multigraph](https://en.wikipedia.org/wiki/Multigraph). Currently we do not have any muligraphs in the JuliaGraphs ecosystem.

**Comment by zhaoli-IHEP** [comment]
> I think what you probably mean is a [multigraph](https://en.wikipedia.org/wiki/Multigraph). Currently we do not have any muligraphs in the JuliaGraphs ecosystem.

Yes. So do I have some other choice in the Julia market? 
Thanks a lot!

**Comment by sbromberger** [comment]
> So do I have some other choice in the Julia market?

I haven't looked closely, but [Graphs.jl](https://github.com/JuliaAttic/Graphs.jl) might be able to do this.

Failing that, you could always write your own data structure and implement the LightGraphs API for it (11 or so functions). Then all the LightGraphs functionality becomes available to your graph type.

If you go that route, publish it :)

**Comment by zhaoli-IHEP** [comment]
> > So do I have some other choice in the Julia market?
> 
> I haven't looked closely, but [Graphs.jl](https://github.com/JuliaAttic/Graphs.jl) might be able to do this.
> 
> Failing that, you could always write your own data structure and implement the LightGraphs API for it (11 or so functions). Then all the LightGraphs functionality becomes available to your graph type.
> 
> If you go that route, publish it :)

Thank you! This is exactly what we need.

**Comment by sbromberger** [comment]
Closing out since it looks like there's a solution. Thanks.
